name: GH-Pages publish

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - gh-pages

jobs:
  build:
    name: build project
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'
    - name: Install Dependencies and build
      run: |
        npm install
        npm run build --if-present
